name: Node.js Package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install @begonaguereca/package@1.0.0 --registry=https://npm.pkg.github.com
