name: Node.js Package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM packages
        run: npm install @begonaguereca/package
